src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank(message: 'Ce champs est obligatoire')]
    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[Assert\NotBlank(message: 'Ce champs est obligatoire')]
    #[ORM\Column(length: 255)]
    private ?string $picture_src = null;

    // propriété utilisée pour le formulaire de modification de produit
    public ?string $update_picture_src = null;

    #[Assert\NotBlank(message: 'Ce champs est obligatoire')]
    #[ORM\Column(length: 255)]
    private ?string $picture_name = null;

    #[Assert\Positive(message: 'Le prix doit être supérieur à 0')]
    #[Assert\NotBlank(message: 'Ce champs est obligatoire')]
    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column]
    private ?bool $disponibility = null;

    #[Assert\NotBlank(message: 'Ce champs est obligatoire')]
    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'products')]
    private Collection $categories;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getPictureSrc(): ?string
    {
        return $this->picture_src;
    }

    public function setPictureSrc(string $picture_src): static
    {
        $this->picture_src = $picture_src;

        return $this;
    }

    public function getPictureName(): ?string
    {
        return $this->picture_name;
    }

    public function setPictureName(string $picture_name): static
    {
        $this->picture_name = $picture_name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function isDisponibility(): ?bool
    {
        return $this->disponibility;
    }

    public function setDisponibility(bool $disponibility): static
    {
        $this->disponibility = $disponibility;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): static
    {
        $this->categories->removeElement($category);

        return $this;
    }
}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Repository\CommandeRepository;
use App\Repository\ProductRepository;
use App\Service\CartService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class FrontController extends AbstractController
{
    // 1er controller pour l'accueil et les pages utilisateur
    // avant cela pour initialisé mon projet j'ai réalisé la commande suivante:
    // composer create-project symfony/skeleton:"6.3.*" art_galery
    // puis:
    // cd art_galery
    //puis:
    // composer require webapp (pour installer les dépendances web. ex le moteur de template twig etc...)
    // ensuite  j'ai créé mon controller avec la commande:
    // php bin/console make:controller front
    // j'ai ensuite configuré mon .env pour la connexion à la bdd
    // et exécuté la commande:
    //  php bin/console doctrine:database:create
    // ensuite j'ai configuré mon base.html.twig de templates pour avoir bootstrap ainsi qu'une barre de navigation.
    // J'ai de même configuré la constante pour le dossier d'upload des images dans le services.yaml dans config avec:
    //  upload: '%kernel.project_dir%/public/upload' , sous parameters
    // a présent il mez faut configuré le twig.yaml dans config/packages pour que les formulaires de symfony utilise bootstrap 5.3
    // form_themes: ['bootstrap_5_layout.html.twig']


    #[Route('/', name: 'home')]
    public function index(ProductRepository $repository, CartService $cartService): Response
    {
      $products=$repository->findBy(['disponibility'=>false]);

//      $cartService->destroy();
//      dd();
        $cart = $cartService->getCartWithData();
        return $this->render('front/index.html.twig', [
            'title' => 'Accueil',
            'products'=>$products,
            'cart' => $cart
        ]);
    }


    #[Route('/cart/add/{id}', name: 'cart_add')]
    public function cart_add(CartService $cartService, $id): Response
    {
        $cartService->add($id);
        $this->addFlash('info', 'Ajouté au panier');
        return $this->redirectToRoute('home');
    }

    #[Route('/cart/remove/{id}/{target}', name: 'cart_remove')]
    public function cart_remove(CartService $cartService, $id,$target): Response
    {
        $cartService->remove($id);
        $this->addFlash('info', 'Retiré du panier');
        // $target sert à gérer la redirection

        if ($target=='home')
        {
            return $this->redirectToRoute('home');

        }else
        {

            return $this->redirectToRoute('fullCart');
        }


    }

    #[Route('/fullCart', name: 'fullCart')]
    public function fullCart(CartService $cartService): Response
    {
        $cart = $cartService->getCartWithData();


        return $this->render('front/cart.html.twig', [
            'cart' => $cart,
            'title'=>'Votre panier'
        ]);
    }




}

templates/front/cart.html.twig
{% extends 'base.html.twig' %}

{% block body %}


    <table class="table table-dark table-striped mt-5 w-75 mx-auto">
        <thead>
        <tr>
            <th>Nom</th>
            <th>Prix</th>
            <th>Photo</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>

        {% for item in cart %}
            <tr>
                <td>{{ item.product.title }}</td>
                <td>{{ item.product.price }}€</td>
                <td><img width="100" src="{{ asset('upload/') }}{{ item.product.pictureSrc }} "
                         alt="{{ item.product.pictureName }}"></td>
                <td>
                    <a href="{{ path('cart_remove', {'id': item.product.id, 'target': 'cart'}) }}" class="btn btn-info">Retirer</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4"><h3 class="text-center">Votre panier est vide</h3></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if app.user %}
        <a href="{{ path('order') }}" class="btn btn-success">Commander </a>
    {% endif %}



{% endblock %}

{% block h1 %}
    {{ title }}
{% endblock %}

{% block title %}
    {{ parent() }}{{ title }}
{% endblock %}

templates/front/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }}{{ title }}{% endblock %}
{% block h1 %}
    {{ title }}
{% endblock %}



{% block body %}
    <div class="row justify-content-between">
        {% for product in products %}


            <div class="col-md-3 card m-3">

                <div class="card-body">
                    <img src="{{ asset('upload/') }}{{ product.pictureSrc }}" class="img-top img-fluid"
                         alt="{{ product.pictureName }}" title="{{ product.pictureName }}">
                </div>

                <div class="card-body">
                    <h3 class="card-title">{{ product.title }}</h3>
                    <h6 class="card-title">{{ product.price }}€</h6>
                </div>

                {% for category  in product.categories %}
                    <span class="w-50 mx-auto border text-center mb-1">{{ category.title }}</span>
                {% endfor %}


                <div class="card-body">
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                            data-bs-target="#exampleModal">
                        Description de l'oeuvre
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                         aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5 text-center" id="exampleModalLabel">Description</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <p>{{ product.description }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    {% set b=0 %}
                    {% for item in cart %}

                        {% if   item.product.id ==product.id %}
                            {% set b=1 %}

                        {% endif %}
                    {% endfor %}
                    {% if b==0 %}
                        <a href="{{ path('cart_add', {'id':product.id}) }}"
                           class="btn btn-info">Ajouter au panier</a>
                    {% else %}
                        <a href="{{ path('cart_remove', {'id':product.id, 'target':'home'}) }}"
                           class="btn btn-warning">Retirer du panier</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>




{% endblock %}

templates/front/orderList.html.twig
{% extends 'base.html.twig' %}
{% block h1 %}
    {{ title }}
{% endblock %}

{% block title %}
    {{ parent() }}{{ title }}
{% endblock %}

{% block body %}

    <table class="table table-dark table-striped mt-5 w-75 mx-auto">
        <thead>
        <tr>
            <th>Nom</th>
            <th>Prix</th>
            <th>Photo</th>
            <th>Date</th>
        </tr>
        </thead>
        <tbody>

        {% for item in commandes %}
            <tr>
                <td >{{ item.product.title }}</td>
                <td>{{ item.product.price }}€</td>
                <td><img width="100" src="{{ asset('upload/') }}{{ item.product.pictureSrc }} " alt="{{ item.product.pictureName }}"></td>
                <td>{{ item.date | date('d/m/Y') }}</td>
            </tr>        {% endfor %}
        </tbody>
    </table>
{% endblock %}